Tag:
  columns:
#    id:
#      type: integer(4)
#      primary: true
#      autoincrement: true
    name:
      type:           string(100)
    is_triple:        
      type:           boolean
    triple_namespace: 
      type:           string(100)
    triple_key:       
      type:           string(100)
    triple_value:     
      type:           string(100)
  indexes:
    name:
      fields: name
    triple1:
      fields: triple_namespace
    triple2:
      fields: triple_key
    triple3:
      fields: triple_value
        
Tagging:
  columns:
#    id:
#      type: integer(4)
#      primary: true
#      autoincrement: true
    tag_id:           
      type:           integer
      notnull:        true
    taggable_model:   
      type:           string(30)
    taggable_id:      
      type:           integer
  relations:
    Tag:
  indexes:
    tag:
      fields: tag_id
    taggable:
      fields: taggable_model, taggable_id